# Generated by Django 4.2 on 2024-01-10 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp_created_at'),
        ('order', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cardDetailId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.carddetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='modeOfPayment',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('ONLINE', 'Online Payment')], default='COD', max_length=10),
        ),
    ]
